### ISSUE TITLE
[wavegrad] [Ascend910] [GPU] Please add some hints about batchsize

### ISSUE THREAD

**Issue by 787918582** [mindspore-lab/mindaudio#112]
wavegrad使用默认配置执行单卡训练时失败，原因是batchsize的默认值为256是执行8p训练时所用，若想跑单卡训练，需要手动将batchsize调成32。请开发帮忙添加些提示说明，方便用户使用
报错截图：
![wavegrad](https://user-images.githubusercontent.com/76412544/227141854-9150d294-e4ea-42bb-bc39-06526b5be11d.png)

**Comment by vigo999** [comment]
bs是参数，这种报错没关系吧。降低bs是常规操作

**Comment by 787918582** [comment]
开发认定为非问题，问题单关闭
