### ISSUE TITLE
[fastspeech2] [GPU] [PYNATIVE] Standalone card train failed

### ISSUE THREAD

**Issue by 787918582** [mindspore-lab/mindaudio#114]
fastspeech2在gpu执行pynative模式的单卡训练时报错
![fastspeech2_1](https://user-images.githubusercontent.com/76412544/227143673-8d8fd61e-5e07-44b7-9564-a35d8556c6f3.png)
![fastspeech2_2](https://user-images.githubusercontent.com/76412544/227143681-9318e106-1eb4-4969-8551-57accbd9560c.png)

**Comment by 787918582** [comment]
版本刷新到0327，仍存在该报错，请尽快解决，谢谢

**Comment by DongyaoZhu** [comment]
done, see pr: fix pr #107

**Comment by DongyaoZhu** [comment]
请问现在的报错是什么？
第二张截图中的442行的代码和最新版本不一样。
执行的git pull; pip install .

**Comment by 787918582** [comment]
报错截图正在外发到蓝区中，稍后上传，请稍等。麻烦您提供下自验成功的执行记录和训练日志，我这边对齐下
