### ISSUE TITLE
readme中代码样例执行失败，缺少librispeech.py文件

### ISSUE THREAD

**Issue by Venomfly** [mindspore-lab/mindaudio#155]
1. 【Document Link】/【文档链接】
https://github.com/mindspore-lab/mindaudio/tree/main
2. 【Issues Section】/【问题文档片段】
Dataset preparation:
python librispeech.py --root_path "your_data_path"
cd ASR
3. 【Existing Issues】/【存在的问题】
缺少librispeech.py文件。缺少 ASR文件夹

**Comment by vigo999** [comment]
https://github.com/mindspore-lab/mindaudio/blob/main/mindaudio/data/librispeech.py
