### ISSUE TITLE
Aishell数据集链接跳转失败未加备注

### ISSUE THREAD

**Issue by Venomfly** [mindspore-lab/mindaudio#157]
1. 【Document Link】/【文档链接】
https://github.com/mindspore-lab/mindaudio/blob/main/examples/qinling-flyspeech/examples/aishell/README.md
2. 【Issues Section】/【问题文档片段】
此示例提供使用[Aishell数据集](http://www.openslr.org/resources/33) 训练以及推理qinling-flyspeech模型的代码。
3. 【Existing Issues】/【存在的问题】
(http://www.openslr.org/resources/33)报504，需在readme中加备注。

**Comment by vigo999** [comment]
qinling folder has been removed
