### ISSUE TITLE
aishell_readme代码样例执行失败

### ISSUE THREAD

**Issue by Venomfly** [mindspore-lab/mindaudio#158]
1. 【Document Link】/【文档链接】
https://github.com/mindspore-lab/mindaudio/blob/main/examples/qinling-flyspeech/examples/aishell/README.md
2. 【Issues Section】/【问题文档片段】
本地训练与推理所有涉及run.sh的操作
bash run.sh --stage -1 --stop_stage 4
3. 【Existing Issues】/【存在的问题】
报错找不到tool文件夹：run.sh: line 89: tools/parse_options.sh: No such file or directory

**Comment by vigo999** [comment]
qinling flyspeech folder has been removed.
