### ISSUE TITLE
wavegrad_README.md中链接跳转无效

### ISSUE THREAD

**Issue by Venomfly** [mindspore-lab/mindaudio#159]
1. 【Document Link】/【文档链接】
https://github.com/mindspore-lab/mindaudio/blob/main/recipes/LJSpeech/tts/wavegrad/README.md
2. 【Issues Section】/【问题文档片段】
Demo:以下两处链接跳转失败：
[sample](https://github.com/mindspore-lab/mindaudio/blob/main/recipes/LJSpeech/tts/wavegrad/results/1000000_predicted_LJ010-0142_1000.wav)
math:
https://github.com/mindspore-lab/mindaudio/blob/main/recipes/LJSpeech/tts/wavegrad/lilianweng.github.io/posts/2021-07-11-diffusion-models
3. 【Existing Issues】/【存在的问题】
请更新有效链接

**Comment by vigo999** [comment]
recipe folder has been removed
