### ISSUE TITLE
wavegrad_README.md代码样例执行失败

### ISSUE THREAD

**Issue by Venomfly** [mindspore-lab/mindaudio#160]
1. 【Document Link】/【文档链接】
https://github.com/mindspore-lab/mindaudio/blob/main/recipes/LJSpeech/tts/wavegrad/README.md
2. 【Issues Section】/【问题文档片段】
Generate from your data：
python recipes/LJSpeech/tts/wavegrad/reverse.py --restore model_1000000.ckpt --wav LJ010-0142.wav --save results --device_target Ascend --device_id 0 --plot
3. 【Existing Issues】/【存在的问题】
直接使用此脚本命令报错：reverse.py: error: argument --plot/-p: expected one argument
--plot需备注说明，或者删除--plot参数。

**Comment by vigo999** [comment]
recipe folder has been removed. please check examples/wavegrad
