### ISSUE TITLE
readme中链接跳转失败（VoxCeleb）

### ISSUE THREAD

**Issue by Venomfly** [mindspore-lab/mindaudio#165]
1. 【Document Link】/【文档链接】
https://github.com/mindspore-lab/mindaudio/blob/main/recipes/VoxCeleb/README_CN.md
https://github.com/mindspore-lab/mindaudio/blob/main/recipes/VoxCeleb/README.md
2. 【Issues Section】/【问题文档片段】
([http://www.robots.ox.ac.uk/~vgg/data/voxceleb/)。](http://www.robots.ox.ac.uk/~vgg/data/voxceleb/)%E3%80%82)
https://download.mindspore.cn/toolkits/mindaudio/ecapatdnn/)%E3%80%82
https://gitee.com/mindspore/models/tree/master/utils/hccl_tools)%E3%80%82
http://www.openslr.org/resources/28/rirs_noises.zip
3. 【Existing Issues】/【存在的问题】
链接跳转失败，404

**Comment by vigo999** [comment]
recipe folder has been removed.
