### ISSUE TITLE
VoxCeleb数据集训练失败

### ISSUE THREAD

**Issue by Venomfly** [mindspore-lab/mindaudio#166]
1. 【Document Link】/【文档链接】
https://github.com/mindspore-lab/mindaudio/blob/main/recipes/VoxCeleb/README_CN.md
https://github.com/mindspore-lab/mindaudio/blob/main/recipes/VoxCeleb/README.md
2. 【Issues Section】/【问题文档片段】
python train_speaker_embeddings.py --need_generate_data=False
bash ./run_distribute_train_ascend.sh hccl.json
3. 【Existing Issues】/【存在的问题】
训练报错：日志如下：
ModuleNotFoundError: No module named 'yaml'

**Comment by vigo999** [comment]
just install yaml please
