### ISSUE TITLE
预训练的模型怎么加载使用和提取向量呢

### ISSUE THREAD

**Issue by lonngxiang** [mindspore-lab/mindaudio#177]
https://github.com/mindspore-lab/mindaudio/blob/main/examples/ECAPA-TDNN/README_CN.md

![image](https://github.com/mindspore-lab/mindaudio/assets/40717349/a9ad27b4-0862-4b43-87a9-793d32890593)

**Comment by LiTingyu1997** [comment]
1.下载weights下的ckpt文件，在yaml配置文件中将pre_trained设置为True，并配置正确的checkpoint_path即可加载预训练模型。

**Comment by LiTingyu1997** [comment]
2.from mindaudio.models.ecapatdnn import EcapaTDNN，并如speaker_verification_cosine.py文件中加载训练好的模型，使用此函数进行推理，即可提取向量。
